### PR TITLE
Added padding to Embedded video

### PR DESCRIPTION
**Pull request by SMak06**
Hi, I'm a student and a newbie at contributing to open source. 

I added top-bottom padding to the embedded video, i think it looks better that way.
But, I had to do it using the <style> tag, coz i was unable to figure out the correct css file for it

Thanks :)

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Hi @SMak06 , thank you for the contribution 👍 . Could you add a before and after screenshot to the pull request please? Also here here is the css file to put the styles `https://github.com/DashboardHub/Website/blob/v0.10-alpha/css/override.css` (in path `/css/override.css`). Nice work and thanks again 🤓

**Comment by eddiejaoude** [comment]
Any questions let me know 🤓

**Comment by SMak06** [comment]
So, I'm unable to figure out this problem. One of the stylesheets is not
loading. What may be the issue?

**Comment by SMak06** [comment]
The vendor folder is missing from the repo actually

**Comment by eddiejaoude** [comment]
Did you run `npm install` first? From the README https://github.com/DashboardHub/Website#installation (I might have missed some steps, I can double check if you still have issues)

**Comment by eddiejaoude** [comment]
No problem 🤓

**Pull request closed without merging**
